name: wandersync
description: A modular travel journal and planner app.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.1
  get_it: ^7.6.4
  equatable: ^2.0.5
  intl: ^0.18.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
